/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostTaskRouteImport } from './routes/post-task'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as TasksCategoriesRouteImport } from './routes/tasks.categories'
import { Route as TasksBrowseRouteImport } from './routes/tasks.browse'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as TasksTaskIdWorkspaceRouteImport } from './routes/tasks.$taskId.workspace'
import { Route as TasksTaskIdApplicationsRouteImport } from './routes/tasks.$taskId.applications'
import { Route as ApiPublicSearchRouteImport } from './routes/api/public/search'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostTaskRoute = PostTaskRouteImport.update({
  id: '/post-task',
  path: '/post-task',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksCategoriesRoute = TasksCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => TasksRoute,
} as any)
const TasksBrowseRoute = TasksBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => TasksRoute,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)
const TasksTaskIdWorkspaceRoute = TasksTaskIdWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => TasksTaskIdRoute,
} as any)
const TasksTaskIdApplicationsRoute = TasksTaskIdApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => TasksTaskIdRoute,
} as any)
const ApiPublicSearchRoute = ApiPublicSearchRouteImport.update({
  id: '/api/public/search',
  path: '/api/public/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/post-task': typeof PostTaskRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/tasks': typeof TasksRouteWithChildren
  '/wallet': typeof WalletRoute
  '/tasks/$taskId': typeof TasksTaskIdRouteWithChildren
  '/tasks/browse': typeof TasksBrowseRoute
  '/tasks/categories': typeof TasksCategoriesRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/public/search': typeof ApiPublicSearchRoute
  '/tasks/$taskId/applications': typeof TasksTaskIdApplicationsRoute
  '/tasks/$taskId/workspace': typeof TasksTaskIdWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/post-task': typeof PostTaskRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/tasks': typeof TasksRouteWithChildren
  '/wallet': typeof WalletRoute
  '/tasks/$taskId': typeof TasksTaskIdRouteWithChildren
  '/tasks/browse': typeof TasksBrowseRoute
  '/tasks/categories': typeof TasksCategoriesRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/public/search': typeof ApiPublicSearchRoute
  '/tasks/$taskId/applications': typeof TasksTaskIdApplicationsRoute
  '/tasks/$taskId/workspace': typeof TasksTaskIdWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/post-task': typeof PostTaskRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/tasks': typeof TasksRouteWithChildren
  '/wallet': typeof WalletRoute
  '/tasks/$taskId': typeof TasksTaskIdRouteWithChildren
  '/tasks/browse': typeof TasksBrowseRoute
  '/tasks/categories': typeof TasksCategoriesRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/public/search': typeof ApiPublicSearchRoute
  '/tasks/$taskId/applications': typeof TasksTaskIdApplicationsRoute
  '/tasks/$taskId/workspace': typeof TasksTaskIdWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/post-task'
    | '/profile'
    | '/register'
    | '/search'
    | '/tasks'
    | '/wallet'
    | '/tasks/$taskId'
    | '/tasks/browse'
    | '/tasks/categories'
    | '/u/$userId'
    | '/api/public/search'
    | '/tasks/$taskId/applications'
    | '/tasks/$taskId/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/post-task'
    | '/profile'
    | '/register'
    | '/search'
    | '/tasks'
    | '/wallet'
    | '/tasks/$taskId'
    | '/tasks/browse'
    | '/tasks/categories'
    | '/u/$userId'
    | '/api/public/search'
    | '/tasks/$taskId/applications'
    | '/tasks/$taskId/workspace'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/post-task'
    | '/profile'
    | '/register'
    | '/search'
    | '/tasks'
    | '/wallet'
    | '/tasks/$taskId'
    | '/tasks/browse'
    | '/tasks/categories'
    | '/u/$userId'
    | '/api/public/search'
    | '/tasks/$taskId/applications'
    | '/tasks/$taskId/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PostTaskRoute: typeof PostTaskRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  TasksRoute: typeof TasksRouteWithChildren
  WalletRoute: typeof WalletRoute
  UUserIdRoute: typeof UUserIdRoute
  ApiPublicSearchRoute: typeof ApiPublicSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-task': {
      id: '/post-task'
      path: '/post-task'
      fullPath: '/post-task'
      preLoaderRoute: typeof PostTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/categories': {
      id: '/tasks/categories'
      path: '/categories'
      fullPath: '/tasks/categories'
      preLoaderRoute: typeof TasksCategoriesRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/browse': {
      id: '/tasks/browse'
      path: '/browse'
      fullPath: '/tasks/browse'
      preLoaderRoute: typeof TasksBrowseRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/$taskId/workspace': {
      id: '/tasks/$taskId/workspace'
      path: '/workspace'
      fullPath: '/tasks/$taskId/workspace'
      preLoaderRoute: typeof TasksTaskIdWorkspaceRouteImport
      parentRoute: typeof TasksTaskIdRoute
    }
    '/tasks/$taskId/applications': {
      id: '/tasks/$taskId/applications'
      path: '/applications'
      fullPath: '/tasks/$taskId/applications'
      preLoaderRoute: typeof TasksTaskIdApplicationsRouteImport
      parentRoute: typeof TasksTaskIdRoute
    }
    '/api/public/search': {
      id: '/api/public/search'
      path: '/api/public/search'
      fullPath: '/api/public/search'
      preLoaderRoute: typeof ApiPublicSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TasksTaskIdRouteChildren {
  TasksTaskIdApplicationsRoute: typeof TasksTaskIdApplicationsRoute
  TasksTaskIdWorkspaceRoute: typeof TasksTaskIdWorkspaceRoute
}

const TasksTaskIdRouteChildren: TasksTaskIdRouteChildren = {
  TasksTaskIdApplicationsRoute: TasksTaskIdApplicationsRoute,
  TasksTaskIdWorkspaceRoute: TasksTaskIdWorkspaceRoute,
}

const TasksTaskIdRouteWithChildren = TasksTaskIdRoute._addFileChildren(
  TasksTaskIdRouteChildren,
)

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRouteWithChildren
  TasksBrowseRoute: typeof TasksBrowseRoute
  TasksCategoriesRoute: typeof TasksCategoriesRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRouteWithChildren,
  TasksBrowseRoute: TasksBrowseRoute,
  TasksCategoriesRoute: TasksCategoriesRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PostTaskRoute: PostTaskRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  TasksRoute: TasksRouteWithChildren,
  WalletRoute: WalletRoute,
  UUserIdRoute: UUserIdRoute,
  ApiPublicSearchRoute: ApiPublicSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
